# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

# theme: minima
remote_theme: "jekyll/minima@4de3223"
title: Dr. Mohammed Alharbi
first_name: Mohammed
middle_name: A.
last_name: Alharbi
author:
  name: Dr. Mohammed A. Alharbi
  email: mahharbi@taibahu.edu.sa
description: # the ">" symbol means to ignore newlines until "footer_text:"
  
footer_text: >
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
keywords: 
lang: en # the language of your site (for example: en, fr, cn, ru, etc.)
icon: #⚛️ the emoji used as the favicon (alternatively, provide image name in /assets/img/)

url: https://mharbi.github.io
baseurl: 
last_updated: false
impressum_path: 
back_to_top: false
# header_pages:
#  - about.md
#  - contact.md

minima:
  date_format: "%b %-d, %Y"
  # social_links:
    # - { icon: "github", title: "Minima Theme repository at GitHub", url: "https://github.com/jekyll/minima" }
  show_excerpts: true
  
# Build settings
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
sass:
  quiet_deps: true
  silence_deprecations: [import]

