# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

theme: minima
title: Mohammed A. Alharbi
first_name: Mohammed
middle_name: M.
last_name: Alharbi
contact_note: >
  
description: > # the ">" symbol means to ignore newlines until "footer_text:"
  
footer_text: >
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
keywords: 
lang: en # the language of your site (for example: en, fr, cn, ru, etc.)
icon: #⚛️ the emoji used as the favicon (alternatively, provide image name in /assets/img/)

url: https://mharbi.github.io
baseurl: 
last_updated: false
impressum_path: 
back_to_top: false
header_pages:
  - about.md
  - contact.md

